import Head from "next/head";
import Image from "next/image";
import { BioRhyme_Expanded, Inter, Titan_One } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Title from "@/components/Title";
import { Container, Box } from "@chakra-ui/react";
import Advertising from "@/components/Advertising";
import Main from "@/components/Main";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Polska Gazeta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display={"flex"} justifyContent={"center"}>
        <Box>
          <Title />
          <Advertising />
          <Main />
        </Box>
      </Box>
    </>
  );
}
